FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY vite.config.* ./
RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine as production

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]