name: pdf-reporting-platform
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pdfplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 3s
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: /Users/mac/pdf-reporting-platform/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - default
      -
networks:
  default:

volumes:
  postgres_data:
