version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

  frontend-dev:
      image: node:22-alpine
      working_dir: /app
      volumes:
        - ./frontend:/app
        - /app/node_modules
      ports:
        - "3000:3000"
      command: sh -c "npm install && npm run dev"
      environment:
        - CHOKIDAR_USEPOLLING=true
      restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdfplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: